language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
notifications:
 email:
  recipients:
   - zac.blanco@rutgers.edu
  on_success: never
  on_failure: always

# command to install dependencies
install: 
 - sudo apt-get install python3-numpy python3-scipy
 - pip install -r requirements.txt
env:
 global:
  - secure: "hgVHcXoWQU20SqXJJmPReWpJOUUeoYAJ4vYodPbzAQmaHH7u8S93cXmaB7gWlJFiGUVSMXWFZF3eF8EPXxydKdJl5SZ7DkFze57JtMrB2slZ9gHQ7rE6U2sLzGfVexpTwhTv1ZhcHtzBAKawo7AFkzLOkVQWwprrIAY0aNUPkzrNV6dwoDPhzQcjVcUayJ6d22KtJaNSpRziWBc7qiIGFvmcUvt1lYrIz2XLfhv7BnTzPv24NzuEmZlMdjpCldDNhm6mjkTvmLSS7NzyL5fX8uzpR0C1m0xqfYQhbNXZFYpbx0BE176VElVcls0hF7yaASLzOzwIUiq0D08yxBTbImJ0lViu4FS4dTomq8jyrgDSfoxBuMCRJ1E42iTTVCy8DwgDjCF9aQ3TNrwx6T+U09U/YrifbGWRuYt9keSOrpZT9y6m8A+JdqWInUc9K+XtOlbsdFbRDvvXHXo00/2dE09UBV/ENg8TQ8fWipbtiz1jfia4UeCf9Yj0g4KqikxphEBqbhYrKBD4w5tal3ueW+0E8iUjFFDc6zUPRXyUW9vLeELUVkD7yYSjE7ZDLfUiWEMu4CgfJ6pDQcgcPl1VzGW7LyhK9KppBw5us7QgaOPrzpjSTb4ZR2x75sDOUr/i/i8Kna4EgfJJb5B6aHeu8buy+fCdXFBLvw2mp+IE5nA="
  - secure: "D7u2r9DZrb1i9YuBQeDaAXc+8tdCBlTXW0My5QMVk8x2WaRKDW1PCnF7mujzXpUrC1VzA4z0dC3tjwshH7rKGbvogTqJu+5JnKemjEAd6qcFMMA6fHVqxpVPKEIyFnovb//NccpWtMKi2CHBwLZn9xM7yn2SzUAOO6L5kbcGgk+QX9FQ8p6DzWkJU0sMDjlsqto4PCLuzn4AT6vlJoob16DDmyBMJLxB3vjLzB421SBBLgChjM4dhvlaJ6tkLAHQh9CPshESnL7FM1AarYSLfX2Bu6NQT4JOJrOPoVmB9ob8YjwTGlINZ7gZRQD0SI3U5wMA2hmb55KdaheWOdU3P7CO0qKF5rFBfD5T5EkzWkhyySu/NhopVcVVvbsEjj897GRhc5h9bD/D16cZlmBKHvzcC+bw/KWmBDBgxO2DxieOdbS2CSM672ArccvJ2Vjxzdm16M+GtiLEJoVw3uuq1OjwCeH+FM+XDpJYzouVTccCTaOmkccu4+QysogFgmNLXEm3hBgxPGLY6pcbu+eKEF89e2KnrXXAyimkRw9BiTVyrfjBQtbZW2CITGEY+esYSFJLfREDPtk2qMbgnoM9EBYcJkss2RkXBQ9rJc1/tDuNyWBBOhXjL3H50RHMGEJdyp9nX66yTRgU7t+eahmxtWj8cxrn6vBS/UiWNlzc1pA="

# command to run tests
script:
 - make test

after_success:
 coveralls
