language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
notifications:
 email:
  recipients:
   - zac.blanco@rutgers.edu
  on_success: never
  on_failure: always

# command to install dependencies
install: 
 - sudo apt-get install python3-numpy python3-scipy
 - pip install -r requirements.txt
env:
 - secure: "XR3Gkkz44QD9Kd+wkvMDMLhQko8ZpqZPAmcUzaT6loweg4NqAxZdmO2KwNDZC/v/ISfG4uk3L8I2sXMFvhFEtASrd/PlfRYOJyoEg4TUTm8S1eqSh2ExWKLg9nipeXTE5jRRK//0oaKCJCt8XJIZuC9HJAGh81STGGVYEf3KkCO9fMjflPHtAjl+UBwDK5h4gk7YgXPTkOuFaE76FGh55cMUf5rZDFIjt8WLhNZh3Jp7ujobQRFWeylzpS72cEu8pLbYaUqcIrTQoQpNWAN3uQl8tDQHO3u5eHCR7SsojbVdYTOILrQtrG5UqbxfX5Ge/8seDc46MmkKutr8xf7CveoyCCkxRAF6Si/i+vnVfTavkqmkfh4bdUBak7scrEoa7Kr89BE5ADCI4MMiaXQLgmnNhxBxnsQtb+Cc+n/18JtEqWmc/9ILjZK+i5tLs36XjlykOf0THUKyyGaB2kXQLTZ9s5dpq7uY5DLf+Ii1Ok268ykl4Qh+QWq8jt0U7rQs/25Hzw8kHfxt6DkC7Gu2Mu+287ePIFXTc0guvnW44hxl2WE7GnW1kOGB7Tyzr+AWPN1mS/geQ8kDeRqhnVTh/u7SdXohC0lXOaIFnf6XhfAFNlKU7P6ZFrOY96w92JqYnBA7DDsMOQW9N/VsmV56xF6YJD5IuSe4zdBeiv/IxMs="
# command to run tests
script:
 - make test

after_success:
 coveralls
