language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
notifications:
 email:
  recipients:
   - zac.blanco@rutgers.edu
  on_success: never
  on_failure: always

# command to install dependencies
install: 
 - sudo apt-get install python3-numpy python3-scipy
 - pip install -r requirements.txt

secure: "gJ9nGt5/u8BSxdZwpCAW+gXFC3dH9zktZIHuDjK7MwsNSCrCH8lO34pRPNrEolCuYuU12NPMBtiPHhlC1ZOzTeIE16uKPu/lySy2nwrPrg+Ljhf2gkAGb57lwCV3qtgRXherImvEDbsyfdEMOVYW4Su10SOxJmh97dRrCqAOUs1Ed3Sqvb0ffEZUqw1aEVOANvUM9KWe9uQQ2QhoGZJTA+sRm4BpY/9NJsitdgOPqOlKOUmcstbU4GjznxU5q033YKa6xARNiAlml0nY1punupqOLR1Z7q6rMDXULjwWMekbccnL6j1RtFDtcPhj9a1c757xXw7QvpbJq+jCWUZmtz/6vWqRq9mshI1F4HdX8QrfzHv5cnU1iGps4lXm74AhFsM0d7+lfro6yN+XlfbEo5gro+B16tFje5FYWExsvLI5vMq07WYxNwmsKagVMxqg/O20iadDYL9GKhgqTF0DZxk46veM6yf1FrYDQAm4uyDLV2uS9sSC5iVYQQI5caosSjroiHb3K3RJcTh6j6YITG6T1NsDyTHZgBiz0vQac0QMwa7KKcqmhG4wfweyXCKqSqvRVZHkbj3Jl4thhFjUM4jj1lNYpmAN6z7oNnLQHmbdhmMYv98gW33kBpK7pzZBM/hrKtCApxldLRx5slzRt01NeoUYVa9MfD0PspcyfpQ="
secure: "bAb1jjGiTch+pFEVVdokaW2AkUEzmQaSZEc0/JzfRNnp08/nZ1NSxHDDZZx+kORgOYEZMyfUVjxWQ5kLf2DHzotvQnEM+oEdjIxA7GAKhFWGecVyRV19tl8Vv3A5MrIH0EzUhlptg0mU0dAxdzZCAFkxOE5mbLpOc+tRFNnAqn+J3LvU8R0dGrzsmFxu4Vh0JnRFPkFrnIFPQRW682AFqaahpP/Z+7E35Hr4sfjLeYGly+shd9Vc0iPV4O+CY16NPmoUomyxGKyWjzKBXVhi/RK9H8IOeW8o0MilQxSYGaAiefeSIPqog5Ha8Rv1boaDIdljuGq7Ezy7QZamA4ft1nkYt7wNRRo2CgGA+AOE/VKK7mNnY2/toUq+POZJtUgHpMMCX5jY/2aYAWlsBnmWQ4cAMoFj7JT3eVo7IzWuCiGk/5UY/PV+3jtIsYq9Rf65UqwhXKq+yZlJZPSdJ0NJXpx4DOP0ct9KZTlGX3Zcpy7ysamYgp8EJPS0z9kg8t1fLqvUtyG6U2n+nDEbeLTCvOl0L+LiDfJNKPgmigZ/BEjzw33MRTWGEQZkhYBnrlH/c1k0Yvma0afuVgD8jBBbFZNaOQHNkVP84Mf1Qu5jNtVKwhlNFrpNpc+wwhB29hjmiozwtoZ2+T1OsGdP9bjKqXYVW/tn+788DLed5rqCfXc="

# command to run tests
script:
 - make test

after_success:
 coveralls
